import Head from "next/head";
import { useRef, useState } from "react";
import VideoContainer from "../components/VideoContainer";

export default function Home() {
  const autoPlay = "?autoplay=1";
  const continuousPlay = "&autoplay=1";
  const [getLink, setGetLink] = useState("");
  const inputLinkValue = useRef();
  const [finalLink, setFinalLink] = useState("");
  const submitLink = (e) => {
    e.preventDefault();
    setGetLink(inputLinkValue.current.value);
    setFinalLink(getLink);
    inputLinkValue.current.value = "";
  };
  console.log(getLink);

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
      </div>

      <form>
        <div className="w-full flex justify-center">
          <input
            placeholder="  write your youtube link"
            ref={inputLinkValue}
            className="w-2/4 border border-sindigo-600 "
          />
          <button
            onClick={submitLink}
            className="bg-indigo-500 px-10 py-5  text-white  rounded-xl"
          >
            submit
          </button>
        </div>
      </form>
      <div className="w-full h-auto border border-red-500">
        <div className="flex w-full justify-center">
          <div>
            <VideoContainer finalLink={finalLink} />
            <button
              className="border bg-sky-300 text-yellow-50 px-6 py-3 rounded-lg mr-3"
              onClick={() => {
                setFinalLink(getLink + "?start=1" + continuousPlay);
              }}
            >
              처음으로
            </button>
            <button
              className="border bg-sky-300 text-yellow-50 px-6 py-3 rounded-lg mr-3"
              onClick={() => {
                setFinalLink(getLink + "?start=448" + continuousPlay);
              }}
            >
              The Lazy Song
            </button>
            <button
              className="border bg-sky-300 text-yellow-50 px-6 py-3 rounded-lg mr-3"
              onClick={() => {
                setFinalLink(getLink + "?start=675" + continuousPlay);
              }}
            >
              I&aposm your
            </button>
            <button
              className="border bg-sky-300 text-yellow-50 px-6 py-3 rounded-lg mr-3"
              onClick={() => {
                setFinalLink(getLink + "?start=2672" + continuousPlay);
              }}
            >
              Still Into You
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

// ("https://www.youtube.com/embed/g0lQESej9zc");
// ("https://www.youtube.com/embed/g0lQESej9zc");
// ("https://www.youtube.com/embed/Irmkb1psaJ0?start=10");
// ("https://www.youtube.com/embed/Irmkb1psaJ0&ab_channel=%EC%98%A4%EB%B6%84%EC%88%9C%EC%82%AD");
// ("https://www.youtube.com/embed/Irmkb1psaJ0&ab_channel=%EC%98%A4%EB%B6%84%EC%88%9C%EC%82%AD");
// "https://www.youtube.com/watch?v=g0lQESej9zc&ab_channel=KenardLau "(
//   "https://www.youtube.com/embed/g0lQESej9zc "
// )("https://www.youtube.com/embed/g0lQESej9zc");
// 유튜브 영상 아이디는 항상 11

// https://www.youtube.com/embed/Irmkb1psaJ0

// https://youtube.com/embed/g0lQESej9zc
